language: java
jdk:
- openjdk11
deploy:
  provider: heroku
  api_key:
    secure: K4y/MAprb3i0VRkQDbUk7+LeLq5q5NLZJY8LP5kTkGwwJIwzvKc3mX5bYhj5b6HlEKRKkEnVP/Pggpy/HQT663Ysg9fh5ciEXFiFli6yNRSyOa5vyGeWF9t10bWPZzIX0biAGlc7S3tYWG+lespic1K+jUB9hPOBX60motNnFQOhkxnsT72WCn3mDl/xz1RI9Wjnexl09hNmtTy68so2Itkag8xlUKHxctgDj3FStdUVcyRHYeAzhJxn3pUYPAtY1Eewy37I4lDbwI7NzA738VahoaE2pCnX7SUWAr3IqykxAYCtyf8dgLriavKgoVdRZmHYVkvyv84ALHQUPOirwmEnDlAOipc/ONdCu3Dl/xy7Y+ZOY7McUI+kQ2DntY1aLJKgoj3EHOlHsD4U5ANbWKMOi+eKCJ9P3hAYQcm3cXDWdWnz3tiwXaeK+d0Lfram0+gmsJ7fq6bn8qiec5r1+sLQzC6M2RxHB4dPjUT7GwZSYClR+xpnZghSfo2PEXoaAfMMBVgmK226Dr5W7+2LIcKKGMcjJIlNpx33bhBpS+DkiBNvw9jkWZo5N1umnKYstawhAco+FlsC4C3ypkEVqv1ENguxZXivCqhBY/Qr5a8MpcxqqmpjvCxFaTI31yoL+6vsI9S9TBPnrOjrL2BWaPQt/lCftNlMsqrtyxWKJhA=
